services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'factory'
      MYSQL_USER: 'users'
      MYSQL_PASSWORD: 'zxcv7890'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
